version: '2.2'

services:
  web:
    container_name: 'chat-server'
    image: 'jihadkhawaja/chat-server:latest'
    build:
      context: ../../src
      dockerfile: MobileChat.Server/Dockerfile
    ports:
      - "5175:80"
    depends_on:
      - "postgres"
    networks:
      - chatserver-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
    # Your Password For Postgres DB
      POSTGRES_PASSWORD: "YourPassword"
    networks:
      - chatserver-network
    ports:
      - "5432:5432"

networks:
  chatserver-network:
    driver: bridge
